# Generated by Django 4.2 on 2025-03-31 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Фото')),
                ('budget_category', models.CharField(choices=[('low', 'До 1 000 руб'), ('medium', '1 000 - 5 000 руб'), ('high', 'От 5 000 руб')], default='medium', max_length=10, verbose_name='Категория бюджета')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('is_consultation', models.BooleanField(default=False, verbose_name='Заявка на консультацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Повод',
                'verbose_name_plural': 'Поводы',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название магазина')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес магазина')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон магазина')),
                ('longitude', models.FloatField(null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(null=True, verbose_name='широта')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_time', models.CharField(blank=True, choices=[('ASAP', 'Как можно скорее'), ('10-12', 'с 10:00 до 12:00'), ('12-14', 'с 12:00 до 14:00'), ('14-16', 'с 14:00 до 16:00'), ('16-18', 'с 16:00 до 18:00'), ('18-20', 'с 18:00 до 20:00')], default='ASAP', max_length=5, verbose_name='Время доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flowers.bouquet', verbose_name='Букет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Количество')),
                ('bouquet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flowers.bouquet', verbose_name='Букет')),
                ('flower', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flowers.flower', verbose_name='Цветок')),
            ],
            options={
                'verbose_name': 'Цветок в букете',
                'verbose_name_plural': 'Цветы в букетах',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(blank=True, through='flowers.BouquetFlower', to='flowers.flower', verbose_name='Цветы в букете'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='occasions',
            field=models.ManyToManyField(blank=True, to='flowers.occasion', verbose_name='Поводы'),
        ),
    ]
