# Generated by Django 4.2 on 2025-03-31 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='quiz_occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowers.occasion'),
        ),
        migrations.AddField(
            model_name='client',
            name='quiz_price_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
