# Generated by Django 3.2.25 on 2025-03-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='buyer_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_phone_deliveries', to='flowers.buyer', verbose_name='телефон покупателя'),
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время консультации')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Выполнена ли консультация')),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_name_consults', to='flowers.buyer', verbose_name='имя покупателя')),
                ('buyer_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_phone_consults', to='flowers.buyer', verbose_name='телефон покупателя')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
    ]
