# Generated by Django 4.2 on 2025-03-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_auto_20250327_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название букета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание букета')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена букета')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название цветка')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветки',
            },
        ),
        migrations.CreateModel(
            name='BouquetReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.bouquet')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.reason')),
            ],
            options={
                'verbose_name': 'Букет по поводу',
                'verbose_name_plural': 'Букет по поводу',
            },
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Количество цветов')),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.bouquet', verbose_name='Название букета')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.flower')),
            ],
            options={
                'verbose_name': 'Букет с цветами',
                'verbose_name_plural': 'Букеты с цветами',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(blank=True, through='flowers.BouquetFlower', to='flowers.flower', verbose_name='Цветы'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='reasons',
            field=models.ManyToManyField(blank=True, through='flowers.BouquetReason', to='flowers.reason', verbose_name='Поводы'),
        ),
    ]
