# Generated by Django 4.2 on 2025-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_bouquet_flower_bouquetreason_bouquetflower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='адрес магазина')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='номер телефона клиента')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('title',),
            },
        ),
    ]
