# Generated by Django 3.2.25 on 2025-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Входит ли в рекомендации'),
        ),
    ]
