# Generated by Django 4.2 on 2025-03-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consult',
            options={'ordering': ('name',), 'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.RemoveField(
            model_name='consult',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='buyer_phone',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='consult_time',
        ),
        migrations.AddField(
            model_name='consult',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='consult',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Выполнена ли консультация'),
        ),
    ]
