# Generated by Django 3.2.25 on 2025-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_bouquet_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='slug',
            field=models.SlugField(default='', max_length=200, verbose_name='Название в виде url'),
        ),
    ]
