# Generated by Django 4.2 on 2025-03-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_alter_consult_options_consult_consult_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя клиента'),
        ),
    ]
