# Generated by Django 3.2.25 on 2025-03-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_auto_20250329_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='heigt',
            new_name='height',
        ),
    ]
