# Generated by Django 4.2 on 2025-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_alter_consult_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='buyer_phone',
        ),
        migrations.AddField(
            model_name='delivery',
            name='buyer_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата и время доставки'),
        ),
    ]
