# Generated by Django 4.2 on 2025-03-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0009_remove_delivery_buyer_phone_delivery_buyer_number_and_more'),
        ('flowers', '0009_rename_heigt_bouquet_height'),
    ]

    operations = [
    ]
