# Generated by Django 4.2 on 2025-03-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0010_merge_20250329_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
