# Generated by Django 4.2 on 2025-03-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0010_merge_20250330_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('is_consultation', models.BooleanField(default=False, verbose_name='Заявка на консультацию')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Повод',
                'verbose_name_plural': 'Поводы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_time', models.CharField(blank=True, choices=[('ASAP', 'Как можно скорее'), ('10-12', 'с 10:00 до 12:00'), ('12-14', 'с 12:00 до 14:00'), ('14-16', 'с 14:00 до 16:00'), ('16-18', 'с 16:00 до 18:00'), ('18-20', 'с 18:00 до 20:00')], default='ASAP', max_length=5, verbose_name='Время доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='bouquetreason',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='bouquetreason',
            name='reason',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Consult',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ['name'], 'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='bouquetflower',
            options={'verbose_name': 'Цветок в букете', 'verbose_name_plural': 'Цветы в букетах'},
        ),
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name': 'Цветок', 'verbose_name_plural': 'Цветы'},
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='reasons',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='title',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='title',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='photo',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='budget_category',
            field=models.CharField(choices=[('low', 'До 1 000 руб'), ('medium', '1 000 - 5 000 руб'), ('high', 'От 5 000 руб')], default='medium', max_length=10, verbose_name='Категория бюджета'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='name',
            field=models.CharField(default='Без названия', max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='flower',
            name='name',
            field=models.CharField(default='Без названия', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(blank=True, through='flowers.BouquetFlower', to='flowers.flower', verbose_name='Цветы в букете'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина (см)'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='bouquet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flowers.bouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='flower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flowers.flower', verbose_name='Цветок'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название магазина'),
        ),
        migrations.DeleteModel(
            name='BouquetReason',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flowers.bouquet', verbose_name='Букет'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flowers.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='occasions',
            field=models.ManyToManyField(blank=True, to='flowers.occasion', verbose_name='Поводы'),
        ),
    ]
