# Generated by Django 4.2 on 2025-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_reason_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачена ли доставка'),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
    ]
