# Generated by Django 4.2 on 2025-03-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0012_alter_client_options_client_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='width',
        ),
    ]
